/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersArchiveRouteImport } from './routes/orders.archive'
import { Route as InvoicesSentRouteImport } from './routes/invoices.sent'
import { Route as DeliveryArchiveRouteImport } from './routes/delivery.archive'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersArchiveRoute = OrdersArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => OrdersRoute,
} as any)
const InvoicesSentRoute = InvoicesSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => InvoicesRoute,
} as any)
const DeliveryArchiveRoute = DeliveryArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => DeliveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/delivery/archive': typeof DeliveryArchiveRoute
  '/invoices/sent': typeof InvoicesSentRoute
  '/orders/archive': typeof OrdersArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/delivery/archive': typeof DeliveryArchiveRoute
  '/invoices/sent': typeof InvoicesSentRoute
  '/orders/archive': typeof OrdersArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/delivery/archive': typeof DeliveryArchiveRoute
  '/invoices/sent': typeof InvoicesSentRoute
  '/orders/archive': typeof OrdersArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/customers'
    | '/delivery'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/users'
    | '/delivery/archive'
    | '/invoices/sent'
    | '/orders/archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/customers'
    | '/delivery'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/users'
    | '/delivery/archive'
    | '/invoices/sent'
    | '/orders/archive'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/customers'
    | '/delivery'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/users'
    | '/delivery/archive'
    | '/invoices/sent'
    | '/orders/archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/archive': {
      id: '/orders/archive'
      path: '/archive'
      fullPath: '/orders/archive'
      preLoaderRoute: typeof OrdersArchiveRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/invoices/sent': {
      id: '/invoices/sent'
      path: '/sent'
      fullPath: '/invoices/sent'
      preLoaderRoute: typeof InvoicesSentRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/delivery/archive': {
      id: '/delivery/archive'
      path: '/archive'
      fullPath: '/delivery/archive'
      preLoaderRoute: typeof DeliveryArchiveRouteImport
      parentRoute: typeof DeliveryRoute
    }
  }
}

interface DeliveryRouteChildren {
  DeliveryArchiveRoute: typeof DeliveryArchiveRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryArchiveRoute: DeliveryArchiveRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesSentRoute: typeof InvoicesSentRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesSentRoute: InvoicesSentRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface OrdersRouteChildren {
  OrdersArchiveRoute: typeof OrdersArchiveRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersArchiveRoute: OrdersArchiveRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  CustomersRoute: CustomersRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
